# Generated by Django 5.1.3 on 2024-11-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('maban', models.AutoField(primary_key=True, serialize=False)),
                ('soghe', models.IntegerField()),
                ('tinhtrang', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'ban',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chitietmonan',
            fields=[
                ('machitiet', models.AutoField(primary_key=True, serialize=False)),
                ('soluong', models.IntegerField()),
                ('thanhtien', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'chitietmonan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Datban',
            fields=[
                ('madatban', models.AutoField(primary_key=True, serialize=False)),
                ('ngay', models.DateField()),
                ('khunggio', models.TimeField()),
                ('trangthai', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'datban',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Khachhang',
            fields=[
                ('makh', models.AutoField(primary_key=True, serialize=False)),
                ('hoten', models.CharField(max_length=100)),
                ('sdt', models.CharField(max_length=15)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'khachhang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Monan',
            fields=[
                ('mamon', models.AutoField(primary_key=True, serialize=False)),
                ('tenmon', models.CharField(max_length=100)),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'monan',
                'managed': False,
            },
        ),
    ]
